# true 시 Reviewer 등록
addReviewers: true

# Assignee 등록
addAssignees: author

# reviewer 명당 (Github id)
reviewers:
  - u0empty
  - jinwooseok

# default는 0이며 0일 때 자신 제외 모든 사람을 reviewer로 포함
numberOfReviewers: 0

# Assignee 1명 할당
numberOfAssignees: 1